appId: vidma.screenrecorder.videorecorder.videoeditor.pro
---
- tapOn:
    id: "rlAudioSetting"
- tapOn:
    id: "lLMicInternal"
- tapOn: "Navigate up"
- tapOn:
    id: "rlVideoSetting"
- tapOn: "Resolution"
- tapOn: "1080P"
- tapOn: "Quality"
- tapOn: "Excellent Quality"
- tapOn: "FPS"
- tapOn: "120FPS"
- tapOn: "Navigate up"
